{% set version = "0.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cols4all
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cols4all_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cols4all/cols4all_{{ version }}.tar.gz
  sha256: 6343255ad93f8164d20de8361aa6a4977714d706bd4293f2bb5ef50c3dfb450e

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-abind
    - r-colorspace >=2.1
    - r-png
    - r-spacesxyz
    - r-stringdist
  run:
    - r-base
    - r-abind
    - r-colorspace >=2.1
    - r-png
    - r-spacesxyz
    - r-stringdist

test:
  commands:
    - $R -e "library('cols4all')"           # [not win]
    - "\"%R%\" -e \"library('cols4all')\""  # [win]

about:
  home: https://mtennekes.github.io/cols4all/, https://github.com/mtennekes/cols4all
  license: GPL-3.0-only
  summary: Color palettes for all people, including those with color vision deficiency. Popular color palette series have been organized by type and have been scored on several properties such as color-blind-friendliness and fairness (i.e. do colors stand out equally?). Own palettes can also be loaded and analysed. Besides
    the common palette types (categorical, sequential, and diverging) it also includes cyclic and bivariate color palettes. Furthermore, a color for missing values is assigned to each palette.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
